//FIRST CHECK IS IS SHREIFF DEAD 

//IF SHERIFF IS DEAD 
        // AND OUTLAW ALIVE = OUTLAW WIN #OUTLAWS FOR LIFE

//ELSE IF REN ALIVE AND DEPUTY ALIVE = OUTLAW WIN  #OUTLAWS FOR LIFE

//ELSE REN WIN!! #RENAGADE MASTER 

//ELSE && SHERIFF ALIVE 
    //AND RENEGAGE/OUTLAW DEAD = LAW WIN!! #I AM THE LAW 

// ELSE CONTIME GAME 

